//
//  LoginInteractor.swift
//  bankibm
//
//  Created by Alexandre Furquim on 02/11/18.
//  Copyright (c) 2018 Alexandre Furquim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func doSomething(request: Login.Something.Request)
    func doLogin(request: Login.loginFields.Request)
}

protocol LoginDataStore {
    var userAccount: UserAccount { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    
    var userAccount = UserAccount()
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""
    
    var isLogged = false
    
    // MARK: Do something
    
    func doSomething(request: Login.Something.Request) {
        worker = LoginWorker()
        worker?.doSomeWork()
        
        let response = Login.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    // MARK: Do login
    func doLogin(request: Login.loginFields.Request) {
        worker = LoginWorker()
        worker?.doLoginRequest(user: request.user, password: request.password) { (success, responseUser) in
            self.isLogged = success
            let response = Login.loginFields.Response(success: success, responseInfo: responseUser!)
            self.userAccount = responseUser!
            self.presenter?.presentLogin(response: response)
        }
    }
        
}
