# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCS_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCS_Challenge
	pod 'Alamofire', '~> 4.8.2'
	pod 'ObjectMapper', '~> 3.4.2'
	
  target 'TCS_ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCS_ChallengeUITests' do
    # Pods for testing
  end

end
