//
//  ExtractWorker.swift
//  TesteSantander
//
//  Created by Hugo Abolis Jordao on 13/06/19.
//  Copyright (c) 2019 Hugo Abolis Jordao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ExtractWorker
{
    func getStatementList(idUser: String, handler: @escaping( (_ response: Extract.Fetch.Response?) -> ()))
    {
        Alamofire.request(Constants.statementListURL + idUser).responseJSON { response in
            switch response.result {
            case .success:
                if let data = response.data{
                    do{
                        let decoder = JSONDecoder()
                        let response = try decoder.decode(Extract.Fetch.Response.self, from: data)
                        handler(response)
                    }catch{
                        print(error)
                        handler(nil)
                    }
                }
            case .failure(let error):
                print(error)
                handler(nil)
            }
        }
    }
}
