//
//  ExtractPresenter.swift
//  TesteSantander
//
//  Created by Hugo Abolis Jordao on 13/06/19.
//  Copyright (c) 2019 Hugo Abolis Jordao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExtractPresentationLogic
{
  func presentSomething(response: Extract.Fetch.Response?)
}

class ExtractPresenter: ExtractPresentationLogic
{
  weak var viewController: ExtractDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Extract.Fetch.Response?)
  {
    
    if let statementList = response?.statementList{
        viewController?.displayStatementList(viewModel: Extract.Fetch.ViewModel(statementList: statementList))
    }else{
        viewController?.displayError(errorMessage: "Ocorreu um erro, por favor tente novamente")
    }
  }
}
