//
//  ExtractWorker.swift
//  TesteSantander
//
//  Created by Hugo Abolis Jordao on 13/06/19.
//  Copyright (c) 2019 Hugo Abolis Jordao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ExtractWorker
{
    func getStatementList(idUser: String, handler: @escaping( (_ response: Extract.Fetch.Response?) -> ()))
    {
        Alamofire.request(Constants.statementListURL + idUser).responseJSON { response in
            self.checkResult(isSuccsess: response.result.isSuccess, data: response.data, handler: handler)
        }
    }
    
    func checkResult(isSuccsess: Bool, data: Data?, handler: @escaping((_ response: Extract.Fetch.Response?) -> ())){
        if isSuccsess{
            if let responseData = data{
                do{
                    let decoder = JSONDecoder()
                    let response = try decoder.decode(Extract.Fetch.Response.self, from: responseData)
                    handler(response)
                }catch{
                    print(error)
                    handler(nil)
                }
            }else{
                handler(nil)
            }
        }else{
            handler(nil)
        }
        
        
    }
}
