# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio_Santander' do
	use_frameworks!
	pod 'Alamofire', '~> 5.0.0-beta.5'
	pod 'CPF-CNPJ-Validator'


end
