//
//  LoginPresenter.swift
//  cleanSwiftProject
//
//  Created by santosw ios samel on 01/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentLogin(response: Login.login.Response)
    func presentUserLastSignIn(response: Login.FetchLastUserSignIns.Response)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic!
    
    // MARK: Do something
    func presentLogin(response: Login.login.Response){
        let viewModel = Login.login.ViewModel(user: response.userResponse, error: response.error!)
        viewController?.displayUserLogin(viewModel: viewModel)
    }
    
    func presentUserLastSignIn(response:Login.FetchLastUserSignIns.Response){
        let viewModel = Login.FetchLastUserSignIns.ViewModel(userName: response.userName)
        viewController.setUsernameLastUserLoggedIn(with: viewModel)
    }
}
