# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AlamofireObjectMapper'
  pod 'RealmSwift'
  pod 'NVActivityIndicatorView'

  target 'TesteiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'TesteiOSUITests' do
  #inherit! :search_paths
  # Pods for testing
end
