# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'TesteIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for TesteIOS
  use_frameworks!
  pod 'RealmSwift'
  pod 'AlamofireObjectMapper'
  pod 'SVProgressHUD'
  
  target 'TesteIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
