platform :ios, '12.0'

target 'TesteIOS' do
    use_frameworks!
    pod 'RealmSwift'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'SVProgressHUD'
    target 'TesteIOSTests' do
        inherit! :search_paths
        pod 'Nimble'
    end
    target 'TesteIOSUITests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
    end
end
