//
//  LoginModels.swift
//  TesteiOSv2
//
//  Created by Macintosh on 15/11/18.
//  Copyright (c) 2018 Roney Sampaio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


enum Login
{
    
    
    // MARK: Request
    struct Request
    {
        var userID: String?
        var password: String?
    }
    
    
    
    // MARK: Response
    struct Response
    {
        var userAccount: [String: Any]?
        var errorMsg: String?
        var success: Bool = false
        
        init(response: [String: Any]) {
            self.userAccount = response[Global.RestParams.LoginRequest.kUserAccount.rawValue] as? [String: Any] ?? [String: Any]()
            let error: [String: Any]? = response[Global.RestParams.ErrorRequest.kError.rawValue] as? [String: Any] ?? [String: Any]()
            
            if self.userAccount?.count ?? 0 > 0  && error?.count == 0 {
                success = true
            } else {
                errorMsg = error?[Global.RestParams.ErrorRequest.kErrorMsg.rawValue] as? String ?? "defaultConnectionError".localized
            }
        }
    }
    
    
    
    // MARK: Account Model
    struct AccountModel
    {
        
        var agency: String
        var balance: Double
        var bankAccount: String
        var name: String
        var userID: Int
        
        
        init(userAccountData: [String: Any]?) {
            self.agency = userAccountData?[Global.RestParams.LoginRequest.kAgency.rawValue] as? String ?? String()
            self.balance = userAccountData?[Global.RestParams.LoginRequest.kBalance.rawValue] as? Double ?? Double()
            self.bankAccount = userAccountData?[Global.RestParams.LoginRequest.kBankAccount.rawValue] as? String ?? String()
            self.name = userAccountData?[Global.RestParams.LoginRequest.kName.rawValue] as? String ?? String()
            self.userID = userAccountData?[Global.RestParams.LoginRequest.kUserID.rawValue] as? Int ?? Int()
        }
    }
}
