//
//  LoginRouter.swift
//  TesteiOSv2
//
//  Created by Macintosh on 15/11/18.
//  Copyright (c) 2018 Roney Sampaio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToDisplayAccount(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToDisplayAccount(segue: UIStoryboardSegue?)
    {
        /*if let segue = segue {
            let destinationVC = segue.destination as! DisplayAccountViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDisplayAccountViewController(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: Global.Constants.accountDetailsStoryboardID, bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: Global.Constants.accountDetailsStoryboardID) as! DisplayAccountViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDisplayAccountViewController(source: dataStore!, destination: &destinationDS)
            navigateToDisplayAccountViewController(source: viewController!, destination: destinationVC)
        }*/
    }
    
    // MARK: Navigation
    
    /*func navigateToDisplayAccountViewController(source: LoginViewController, destination: DisplayAccountViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToDisplayAccountViewController(source: LoginDataStore, destination: inout DisplayAccountDataStore)
    {
        destination.accountData = source.loginData
    }*/
}
