//
//  StatementModels.swift
//  TestSantander-IBM
//
//  Created by Renato Carvalhan on 22/01/19.
//  Copyright (c) 2019 Renato Carvalhan. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct StatementScene {
    
    struct GetStatements {
        
        struct Request {
            var id = 0
        }
        
        struct Response {
            var statements: [Statement]
            var error: Error?
        }
    }
    
    struct Error {
        var code: Int
        var message: String
    }
}
