//
//  StatementPresenter.swift
//  TestSantander-IBM
//
//  Created by Renato Carvalhan on 22/01/19.
//  Copyright (c) 2019 Renato Carvalhan. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol StatementPresenterInput {
    func presentStatements(response: StatementScene.GetStatements.Response)
}

protocol StatementPresenterOutput: class {
    func displayStatements(response: StatementScene.GetStatements.Response)
}

class StatementPresenter: StatementPresenterInput {
    
    weak var output: StatementPresenterOutput?
    
    // MARK: Presentation logic
    
    func presentStatements(response: StatementScene.GetStatements.Response) {
        output?.displayStatements(response: response)
    }
}
