//
//  StatementsListInteractor.swift
//  Bank_App
//
//  Created by apple on 21/03/20.
//  Copyright (c) 2020 Barbara_Aniele. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsListBusinessLogic {
  func logout()
  func getList(_ request: StatementsList.Request)
}

protocol StatementsListDataStore {
  var userInfo: UserAccount? { get set }
}

class StatementsListInteractor: StatementsListBusinessLogic, StatementsListDataStore {
  
  var presenter: StatementsListPresentationLogic?
  var worker: StatementsListWorker?
  
  var userInfo: UserAccount?
  var error: String = ""
  var statementsList: StatementsList.ViewModel?
  
  // MARK: Do something
  
  func logout() {
    Keychain.removeValue(forKey: "userLogin")
  }
  
  func getList(_ request: StatementsList.Request) {
    worker = StatementsListWorker()
    worker?.getList(request: request, completion: { (result: StatementsResponse) in
      guard let _ = result.statementList else {
        self.error = result.error?.message ?? "Erro ao carregar lista"
        self.presenter?.presentError(error: self.error)
        return
      }
      
      let response = StatementsList.ViewModel(statementsList: result.statementList)
      self.statementsList = response
      self.presenter?.presentSucess(response: response)
    })
  }
}
