//
//  StatementsListWorker.swift
//  Bank_App
//
//  Created by apple on 21/03/20.
//  Copyright (c) 2020 Barbara_Aniele. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class StatementsListWorker {
  
  func getList(request: StatementsList.Request, completion: @escaping (StatementsResponse) -> ()) {
    let userId = String(request.userId)
    let path = "https://bank-app-test.herokuapp.com/api/statements/" + userId
    let headers: [String: String] = ["Content-Type": "application/x-www-form-urlencoded"]
    Alamofire.request(path, method: .get, headers: headers).responseData(completionHandler: { response in
      if let value = response.result.value {
        let response = try! JSONDecoder().decode(StatementsResponse.self, from: value)
        completion(response)
      }
    })
  }
}
