//
//  StatementsListViewController.swift
//  Bank_App
//
//  Created by apple on 21/03/20.
//  Copyright (c) 2020 Barbara_Aniele. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsListDisplayLogic: class {
  func displayStatementsList(viewModel: StatementsList.ViewModel)
  func displayError(_ message: String?)
}

class StatementsListViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, StatementsListDisplayLogic {
  
  var interactor: StatementsListBusinessLogic?
  var router: (NSObjectProtocol & StatementsListRoutingLogic & StatementsListDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = StatementsListInteractor()
    let presenter = StatementsListPresenter()
    let router = StatementsListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    preencherDados()
    preencherLista()
    self.tableView.delegate = self
    self.tableView.dataSource = self
    self.tableView.register(UINib(nibName: "StatementsTableViewCell", bundle: nil), forCellReuseIdentifier: "statementsTableViewCell")
  }
  
  //MARK: TableView
  
  @IBOutlet weak var tableView: UITableView!
  
  var statementsList: StatementsList.ViewModel = StatementsList.ViewModel(statementsList: [])
  
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return statementsList.statementsList?.count ?? 0
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    if let cell = tableView.dequeueReusableCell(withIdentifier: "statementsTableViewCell") as? StatementsTableViewCell {
      cell.configureCell(cellInfo: statementsList.statementsList?[indexPath.row])
      return cell
    }
    return UITableViewCell()
  }
  
  func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
    return 104
  }
  
  // MARK: Preencher Dados
  
  @IBOutlet weak var nomeLabel: UILabel!
  @IBOutlet weak var contaLabel: UILabel!
  @IBOutlet weak var saldoLabel: UILabel!
  
  func preencherDados() {
    if let dataStore = self.router?.dataStore, let userData = dataStore.userInfo {
      nomeLabel.text = userData.name
      saldoLabel.text = userData.balance?.formatCurrency(valor: userData.balance! as NSNumber)
      contaLabel.text = (userData.bankAccount ?? "") + " / " + (userData.agency ?? "")
    }
  }
  
  func preencherLista() {
    let userId = self.router?.dataStore?.userInfo?.userId
    let request = StatementsList.Request(userId: userId ?? -1)
    interactor?.getList(request)
  }
  
  @IBAction func logoutTapped(_ sender: Any) {
    interactor?.logout()
    router?.routeToLoginScreen(vc: self)
  }
  
  func displayStatementsList(viewModel: StatementsList.ViewModel) {
    statementsList = viewModel
    tableView.reloadData()
    hideActivityIndicator()
  }
  
  func displayError(_ message: String?) {
    hideActivityIndicator()
    showAlertErrorMessage(message: message ?? "Erro ao carregar lista")
  }
  
  func showActivityIndicator() {
    let activityIndicator:LoadingView = LoadingView(frame: CGRect(x: 0, y: 0, width: view.frame.width, height: view.frame.height))
    activityIndicator.tag = 10000
    self.view.addSubview(activityIndicator)
  }
  
  func hideActivityIndicator() {
    if let activityIndicator = self.view.viewWithTag(10000) {
      activityIndicator.removeFromSuperview()
    }
  }
}
