# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'MyBankApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyBankApp
  pod 'SnapKit'
  pod 'PromiseKit'

  target 'MyBankAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting'
  end

  target 'MyBankAppUITests' do
    # Pods for testing
  end

end
