//
//  StatementsPresenter.swift
//  BankApp
//
//  Created by Joni Campos on 19/09/19.
//  Copyright (c) 2019 Joni Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsPresentationLogic
{
    func presentStatement(_ response: Statement.StatementApi.Response)
}

class StatementsPresenter: StatementsPresentationLogic
{
    weak var viewController: StatementsDisplayLogic?
    
    func presentStatement(_ response: Statement.StatementApi.Response) {
        viewController?.showStatement(statements: response)
    }
    
}

