//
//  StatementsInteractor.swift
//  BankApp
//
//  Created by Joni Campos on 19/09/19.
//  Copyright (c) 2019 Joni Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import UIKit

protocol StatementsBusinessLogic
{
    func getStatement(request: Statement.StatementApi.Request)
}

protocol StatementsDataStore
{
    var user: Login.Something.User! { get set }
    //var name: String { get set }
}

class StatementsInteractor: StatementsBusinessLogic, StatementsDataStore
{
    var user: Login.Something.User!
    var presenter: StatementsPresentationLogic?
    var worker: StatementsWorker?
   
    
    // MARK: Do something
    func getStatement(request: Statement.StatementApi.Request)
    {
        worker = StatementsWorker(StatementsService())
        worker?.getStatement(request.userId) { (response: [Login.Something.StatementUser]) in
            let response = Statement.StatementApi.Response(statement: response)
            DispatchQueue.main.async {
                self.presenter?.presentStatement(response)
            }
        }
    }
}
