//
//  HomeModels.swift
//  KssiusBank
//
//  Created by Cassio Sousa on 17/06/23.
//  Copyright (c) 2023 Cassio Sousa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum GetStatements
  {
    struct Request{}

    struct Response{
        let statements: [StatementsModel]

        // MARK: - Inits

        init(statements: [StatementsModel]) {
            self.statements = statements
        }
    }

    struct ViewModel{

        // MARK: - Properties

        let statements: [StatementsModel]
        let success: Bool

        // MARK: - Inits

        init(statements: [StatementsModel], success: Bool) {
            self.statements = statements
            self.success = success
        }
    }
  }
}
