//
//  HomeModels.swift
//  KssiusBank
//
//  Created by Cassio Sousa on 17/06/23.
//  Copyright (c) 2023 Cassio Sousa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases

    enum GetStatements
    {
        struct Request{}

        struct Response{
            let success: Bool
            let errorMessage: String?
            let statements: [StatementsModel]

            init(success: Bool = true, errorMessage: String? = nil, statements: [StatementsModel] = []) {
                self.success = success
                self.errorMessage = errorMessage
                self.statements = statements
            }

            func toViewModel() -> ViewModel {
                return .init(statements: statements, success: success)
            }
        }

        struct ViewModel{

            // MARK: - Properties

            let statements: [StatementsModel]
            let success: Bool

            // MARK: - Inits

            init(statements: [StatementsModel], success: Bool) {
                self.statements = statements
                self.success = success
            }
        }
    }

    enum GetAccount
    {
        struct Request{}

        struct Response{
            let userAccount: UserAccountModel

            init(userAccount: UserAccountModel) {
                self.userAccount = userAccount
            }

            func toViewModel() -> ViewModel {
                return .init(name: userAccount.name,
                             agency: userAccount.agency,
                             accountNumber: userAccount.accountNumber,
                             balance: userAccount.balance)
            }
        }

        struct ViewModel{

            // MARK: - Properties

            let name: String
            let agency: String
            let accountNumber: String
            let balance: Double

            // MARK: - Inits

            init(name: String,
                 agency: String,
                 accountNumber: String,
                 balance: Double){
                self.name = name
                self.agency = agency
                self.accountNumber = accountNumber
                self.balance = balance
            }
        }
    }
}
