# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TataSantanderBankTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TataSantanderBankTest
  pod 'Alamofire'

  target 'TataSantanderBankTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
