# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'
use_frameworks!
target 'Teste Santander' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'Alamofire', '4.8.2'
  pod 'SDWebImage', '4.4.6'
  pod 'ObjectMapper', '3.4.1'
  pod 'RNLoadingButton-Swift'
  pod 'KeychainSwift', '15.0.0'
  pod 'RNActivityView'
  pod 'CPF-CNPJ-Validator'
  # Pods for Teste Santander

  target 'Teste SantanderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '1.3.4'
    pod 'Nimble', '8.0.0'
  end

end


