//
//  StatementWorker.swift
//  BankApp
//
//  Created by Marcus Titton on 19/09/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//Criação de protocolo
protocol StatementDataProtocol {
    func getStatements(_ id: Int, completionHandler: @escaping ([StatementUser]) -> Void)
    func mockStatements(_ id: Int, completionHandler: @escaping ([StatementUser]) -> Void)
}

class StatementWorker
{
    //Inicialização de variavel com o protocolo
    var statementData: StatementDataProtocol
    
    //Inicialização do protocolo
    init(_ statementData: StatementDataProtocol) {
        self.statementData = statementData
    }
    
    //Função de captura de extrato (que fará a requisição para o serviço da API)
    func getStatement(_ id: Int, completionHandler: @escaping ([StatementUser]) -> Void) {
        statementData.getStatements(id, completionHandler: completionHandler)
    }
    
    //Função de captura de extrato (que fará a requisição para o serviço da API)
    func mockStatement(_ id: Int, completionHandler: @escaping ([StatementUser]) -> Void) {
        statementData.mockStatements(id, completionHandler: completionHandler)
    }
}

