//
//  StatementPresenter.swift
//  TesteiOSv2_ArlenPereira
//
//  Created by Arlen Ricardo Pereira on 28/01/20.
//  Copyright (c) 2020 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsPresentationLogic
{
  func presentUserInfo(response: StatementsModel.UserInfoModel.Response)
}

class StatementsPresenter: StatementsPresentationLogic
{
  weak var viewController: StatementDisplayLogic?
  
  // MARK: Function
  
  func presentUserInfo(response: StatementsModel.UserInfoModel.Response)
  {
    var dataResult: StatementsModel.UserInfoModel.ViewModel!
    
    if !response.userInfoResponse.data!.isEmpty {
        for item in response.userInfoResponse.data! {
            dataResult = StatementsModel.UserInfoModel.ViewModel(userId: item.userId,
                                                                 name: item.name,
                                                                 bankAccount: item.bankAccount,
                                                                 agency: item.agency,
                                                                 balance: item.balance)
        }
    }
    viewController?.displayStatements(viewModel: dataResult)
  }
}
