//
//  UserWorker.swift
//  santander-challenge
//
//  Created by Kevin Oliveira on 01/05/20.
//  Copyright (c) 2020 Kevin Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol UserWorkerLogic {
    func saveUser(_ user: String?)
    func getUser() -> String?
}

class UserWorker: UserWorkerLogic {
    func saveUser(_ user: String?) {
        UserDefaults.standard.set(user, forKey: "user")
    }

    func getUser() -> String? {
        return UserDefaults.standard.string(forKey: "user")
    }
}
