//
//  UserDataWorker.swift
//  Bank App
//
//  Created by Christian Castro on 02/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UserDataWorker {

    func saveUser(user: String, password: String) {
        KeychainWrapper.standard.set(user, forKey: "bank.app.user")
        KeychainWrapper.standard.set(password, forKey: "bank.app.password")
    }
            
    func fetchCurrentUser() -> String {
        guard let user = KeychainWrapper.standard.string(forKey: "bank.app.user")
        else { return "" }
        return user
    }
    
    func fetchCurrentPassword() -> String {
        guard let password = KeychainWrapper.standard.string(forKey: "bank.app.password")
        else { return "" }
        return password
    }
    
    func checkUsersField(user: String) -> Bool {
        let isValidUser = Validator.validateUser(user: user)
        return isValidUser
    }
    
    func checkPasswordField(password: String) -> Bool {
        let isValidPassword = Validator.validatePassword(password: password)
        return isValidPassword
    }
}
