# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bank
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'SwiftMessages'
  pod 'IHProgressHUD'
  pod 'KeychainSwift'

  target 'BankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankUITests' do
    # Pods for testing
  end

end
