//
//  LoginWorker.swift
//  BankApp
//
//  Created by Joni Campos on 19/09/19.
//  Copyright (c) 2019 Joni Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation



class LoginWorker
{
    var loginProt: LoginProtocol
    
    //inicializa
    init(_ loginProt: LoginProtocol) {
        self.loginProt = loginProt
    }
    
    
    //chama aqui a rotina de login com o completionhandler para aguardar a volta dos dados...a rotina retorna para o Login Interactor
    func login(_ login: String, password: String, completionHandler: @escaping (Login.Something.User?) -> Void)
    
    {
        loginProt.login(login, password: password, completionHandler: completionHandler)
    }
}



    
