//
//  LoginModels.swift
//  BankApp
//
//  Created by Joni Campos on 19/09/19.
//  Copyright (c) 2019 Joni Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    
    struct User: Decodable{
        let userId: Int
        let name: String
        let bankAccount: String
        let agency: String
        let balance: Double
        
    }
    
    
    
   
    
    struct Request
    {
        var user:String?
        var password:String?
    }
    struct Response
    {
        var result:User?
    }
    struct ViewModel
    {
        
    }
  }
}


