//
//  LoginWorker.swift
//  BankApp
//
//  Created by resource on 16/06/19.
//  Copyright (c) 2019 Gabriel Faustino. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {
    private var apiLayer = NetworkLayerAlamofire()
    
    func loginUser(_ user: Login.User.Request, success: ((Login.User.Response) -> Void)?, failure: ((Error) -> Void)? ) {
        let url = URL(string: "https://bank-app-test.herokuapp.com/api/login")!
        let parameters: [String : Any] = ["user": user.user!, "password": user.password!]
        let headers = ["Content-Type": "application/x-www-form-urlencoded"]
        
        apiLayer.post(url, model: Login.User.Response.self, params: parameters, headers: headers) { result in
            switch result {
            case .success(let loginData):
                success?(loginData)
            case .failure(let error):
                failure?(error)
            }
        }
    }
    
    func getUserPersisted() -> String? {
        return UserDefaults.standard.string(forKey: Constants.Persistence.login)
    }
    
    func setUserToPersistence(_ user: String) {
        UserDefaults.standard.set(user, forKey: Constants.Persistence.login)
    }
}
