//
//  StatementListModels.swift
//  bankibm
//
//  Created by Alexandre Furquim on 02/11/18.
//  Copyright (c) 2018 Alexandre Furquim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Register {
    var title : String
    var desc : String
    var date : String
    var value : Float
}


enum StatementList {
    // MARK: Use cases
    
    enum Something {
        struct Request {
            
        }
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum GetUserAccount {
        struct Request{
            
        }
        
        struct Response {
            var userAccount: UserAccount
        }
        
        struct ViewModel {
            struct DisplayedUserAccount {
                var userId : String?
                var name : String?
                var bankAccount : String?
                var agency : String?
                var balance : String?
            }
            
            var displayedUserAccount: DisplayedUserAccount
            
        }
    }
    
    struct DisplayedRegister {
        var title : String
        var desc : String
        var date : String
        var value : String
    }
    
    enum FetchRegisters {
        struct Request {
            var userId: String
        }
        
        struct Response {
            var success: Bool
            var registers: [Register]
        }
        
        struct ViewModel {
            var displayedRegisters: [DisplayedRegister]
            var success: Bool
        }
    }
    
}
