//
//  LoginWorker.swift
//  TesteSantander
//
//  Created by Hugo Abolis Jordao on 13/06/19.
//  Copyright (c) 2019 Hugo Abolis Jordao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class LoginWorker
{
    
    func login(user: String, password: String, handler: @escaping((_ response: Login.Fetch.Response?) -> ()) ){
        let parameters =  ["user": user, "password": password]
        
        Alamofire.request(Constants.loginURL, method: .post, parameters: parameters, encoding: URLEncoding.default).responseJSON { response in
            
            self.checkResult(isSuccsess: response.result.isSuccess, data: response.data, handler: handler)
        }
    }
    
    func checkResult(isSuccsess: Bool, data: Data?, handler: @escaping((_ response: Login.Fetch.Response?) -> ())){
        if isSuccsess{
            if let responseData = data{
                do{
                    let decoder = JSONDecoder()
                    let response = try decoder.decode(Login.Fetch.Response.self, from: responseData)
                    handler(response)
                }catch{
                    print(error)
                    handler(nil)
                }
            }else{
                handler(nil)
            }
        }else{
            handler(nil)
        }
        
        
    }
    
    
}
