//
//  HomeModels.swift
//  Bank
//
//  Created by Matheus Rodrigues Ribeiro on 25/04/20.
//  Copyright (c) 2020 Bank. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
    enum UserData
    {
        struct ViewModel
        {
            var id: Int
            var name: String
            var agency: String
            var account: String
            var balance: Float
        }
    }
    
    enum StatementList {
        struct Request
        {
            var userId: Int
        }
        
        struct ViewModel
        {
            var statements: [Statement]
        }
        
        struct Statement
        {
            var transaction: String
            var description: String
            var date: String
            var value: String
        }
        
        struct Error {
            var title: String?
            var message: String?
        }
    }
}
