# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Williamberg Bank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'
  pod 'SwiftKeychainWrapper'
  pod 'Mockingjay'

  # Pods for Williamberg Bank

  target 'Williamberg BankTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay'
  end

  target 'Williamberg BankUITests' do
    # Pods for testing
  end

end
