//
//  AccountDetailsPresenter.swift
//  TesteIOS
//
//  Created by VM on 26/07/20.
//  Copyright (c) 2020 VM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDetailsPresentationLogig {
    func presenterFetchAccountDetails(response: AccountDetailsModel.Fetch.Response)
    func presentFetchError(error: String)
    func setupHeader(data: AccountDetailsModel.Header.Response)
}

class AccountDetailsPresenter: AccountDetailsPresentationLogig {
    
    weak var viewController: AccountDetailsDisplayLogig?
  
    func presenterFetchAccountDetails(response: AccountDetailsModel.Fetch.Response) {
        guard let statementList = response.statements?.statementList else { return }
        let list = statementList.sorted(by: { $0.date?.toDate().compare($1.date?.toDate() ?? Date()) == .orderedDescending })
        
        let viewModel = AccountDetailsModel.Fetch.ViewModel(statementEntries: list)

        viewController?.displayData(viewModel: viewModel)
    }
    
    func presentFetchError(error: String) {
        
    }
    
    func setupHeader(data: AccountDetailsModel.Header.Response) {
        let name = data.headerData?.name ?? ""
        let account = "\(data.headerData?.bankAccount ?? "")/\(data.headerData?.agency ?? "")"
        let balance = data.headerData?.balance?.currencyFormatted() ?? "R$ 0,00"
        let viewModel = AccountDetailsModel.Header.ViewModel(name: name,
                                                         account: account,
                                                         balance: balance)
        viewController?.displayHeaderData(viewModel: viewModel)
    }
    
}
