//
//  LoginModels.swift
//  TesteiOSv2
//
//  Created by Alexandre Gabassi on 29/10/18.
//  Copyright (c) 2018 Alexandre Gabassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum LoginFormFields
  {
    struct Request
    {
        var user: String
        var password: String
    }
    struct Response
    {
        var success: Bool
        var info: UserInfo
    }
    struct ViewModel
    {
        var success: Bool
        var greeting: String
    }
  }
}
