# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SANTANDER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SANTANDER

  target 'SANTANDERTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SANTANDERUITests' do
    # Pods for testing
  end

pod 'CPF-CNPJ-Validator'
pod 'Alamofire'



end
