//
//  StatementWorker.swift
//  BankApp
//
//  Created by Lynneker Souza on 5/29/20.
//  Copyright (c) 2020 Lynneker Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StatementWorker
{
    var statementStore: StatementStoreProtocol
    
    init(statementStore: StatementStoreProtocol) {
        self.statementStore = statementStore
    }
    
    func fetchOrders(completionHandler: @escaping ([Statement]) -> Void)
    {
        statementStore.fetchStatement { (statement: [Statement]) -> Void in
            let orders = statement
            DispatchQueue.main.async {
                completionHandler(orders)
            }
        }
    }
    
}

protocol StatementStoreProtocol
{
    func fetchStatement(completionHandler: @escaping ([Statement]) -> Void)
}
