# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya' #, '~> 14.0'
  pod 'KeychainSwift', '~> 19.0'

  # Pods for BankTest
  target 'BankTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya' #, '~> 14.0'
  end

end
