# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOSv2_ArlenPereira' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteiOSv2_ArlenPereira
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'JGProgressHUD', '2.1.0'
  pod 'CPF-CNPJ-Validator', '1.0.2'
  pod 'KeychainSwift', '19.0.0'

end
