# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOSv2Acc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteiOSv2Acc
  pod 'Alamofire', '4.8.2'
  pod 'CPF-CNPJ-Validator', '1.0.2'
  pod 'KeychainAccess', '3.2.0'
  pod 'IQKeyboardManager', '6.3.0'

  target 'TesteiOSv2AccTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
