//
//  StatementsInteractor.swift
//  Williamberg Bank
//
//  Created by padrao on 23/05/20.
//  Copyright (c) 2020 Williamberg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsBusinessLogic
{
    func loadUserAccount(request: Statements.LoadUserAccount.Request)
}

protocol StatementsDataStore
{
  var userAccount: UserAccount? { get set }
}

class StatementsInteractor: StatementsBusinessLogic, StatementsDataStore
{
  var presenter: StatementsPresentationLogic?
  var worker: StatementsWorker?
  var userAccount: UserAccount?
  
  // MARK: Do something
  
    func loadUserAccount(request: Statements.LoadUserAccount.Request)
  {
    worker = StatementsWorker()
    worker?.doSomeWork()
    
    let response = Statements.LoadUserAccount.Response(userAccount: userAccount)
    presenter?.presentUserAccount(response: response)
  }
}
