//
//  LoginModels.swift
//  BankApp
//
//  Created by Victor Lisboa on 20/09/19.
//  Copyright (c) 2019 Victor Lisboa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request: Decodable {
            var user: String?
            var password: String?
        }
        
        struct Response: Decodable {
            var userAccount: UserAccount?
            var error: Error?
        }
        
        struct UserAccount: Decodable {
            var userId: Int?
            var name: String?
            var bankAccount: String?
            var agency: String?
            var balance: Double?
        }
        
        struct Error: Decodable {
            var code: Int?
            var message: String?
        }
    }
}
