//
//  LoginPresenter.swift
//  BankApp
//
//  Created by Victor Lisboa on 20/09/19.
//  Copyright (c) 2019 Victor Lisboa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
//  func presentSomething(response: Login.Something.Response)
    func presentLogin()
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: Login.Something.Response)
//  {
////    let viewModel = Login.Something.ViewModel()
////    viewController?.displaySomething(viewModel: viewModel)
//  }
    func presentLogin() {
        viewController?.presentExtrato()
    }
}
