# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SantanderTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod "PromiseKit"
  pod 'SVProgressHUD'
  pod 'SnapKit'
  pod 'SwiftKeychainWrapper'
  # Pods for SantanderTest

  target 'SantanderTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SantanderTestUITests' do
    # Pods for testing
  end

end
