//
//  LoginViewController.swift
//  TesteIOS
//
//  Created by khalid ait bellahs on 21/01/19.
//  Copyright (c) 2019 ti alto nivel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
    func displayStatmentView()
}

class LoginViewController: UIViewController, LoginDisplayLogic {
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

    @IBOutlet var loginButton: UIButton!
    @IBOutlet var userInput: UITextField!
    @IBOutlet var passwordInput: UITextField!

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        loginButton.layer.cornerRadius = 4.0
        userInput.layer.borderWidth = 1
        userInput.layer.cornerRadius = 4.0
        userInput.layer.borderColor = UIColor(red: 220, green: 226, blue: 238, alpha: 1).cgColor
        passwordInput.layer.borderWidth = 1
        passwordInput.layer.cornerRadius = 4.0
        passwordInput.layer.borderColor = UIColor(red: 220, green: 226, blue: 238, alpha: 1).cgColor

    }

    @IBAction func LoginClick(_ sender: Any) {
        doLogin()
    }


    func doLogin() {
        let request = Login.doLogin.Request(user: userInput.text!, password: passwordInput.text!)
        interactor?.doLogin(request: request)
    }

    func displayStatmentView() {
        
        let mainStoryBoard = UIStoryboard(name: "Main", bundle: Bundle.main)
        guard let statmentsView = mainStoryBoard.instantiateViewController(withIdentifier: "statementsViewController") as? statementsViewController else {
            print("couldn't find view")
            return
        }
        print("deu certo rsrs")
        statmentsView.modalTransitionStyle = .flipHorizontal
        present(statmentsView, animated: true, completion: nil)
        
    }
}
