//
//  LoginSceneModels.swift
//  TesteiOSv2
//
//  Created by Vlad Lopes on 14/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginScene
{
  // MARK: Login treatment
  
  enum ReadLogin
  {
    struct Request
    {
    }
    struct Response
    {
        var login: String
    }
    struct ViewModel
    {
        var login: String
    }
  }
    
    enum StoreLogin
    {
      struct Request
      {
          var login: String
      }
      struct Response
      {
          
      }
      struct ViewModel
      {
          
      }
    }
    
    enum ValidateLogin
    {
      struct Request
      {
        var login: String
        var password: String
      }
      struct Response
      {
            var alertMessage: String
      }
      struct ViewModel
      {
            var alertMessage: String
      }
    }
}
