//
//  LoginSceneRouter.swift
//  TesteiOSv2
//
//  Created by Vlad Lopes on 14/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginSceneRoutingLogic
{
  func routeToAccountScene(segue: UIStoryboardSegue?)
}

protocol LoginSceneDataPassing
{
  var dataStore: LoginSceneDataStore? { get }
}

class LoginSceneRouter: NSObject, LoginSceneRoutingLogic, LoginSceneDataPassing
{
  weak var viewController: LoginSceneViewController?
  var dataStore: LoginSceneDataStore?
  
  // MARK: Routing
  
  func routeToAccountScene(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! AccountSceneViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToAccount(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "AccountSceneViewController") as! AccountSceneViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToAccount(source: dataStore!, destination: &destinationDS)
      navigateToAccount(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToAccount(source: LoginSceneViewController, destination: AccountSceneViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToAccount(source: LoginSceneDataStore, destination: inout AccountSceneDataStore)
  {
    destination.clientLogged = source.clientLogged
  }
}
