//
//  StatementPresenter.swift
//  TesteiOSv2
//
//  Created by jeffersoncsilva on 08/02/2019.
//  Copyright (c) 2019 Accenture. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols
protocol StatementPresentationLogic
{
    func presentLoading()
    func removeLoading()
    func presentStatements(response: Statement.StatementModels.Response)
}

//MARK: - Class body
class StatementPresenter: StatementPresentationLogic
{
    //MARK: - Properties
    weak var viewController: StatementDisplayLogic?
    
    //MARK: - Functions
    func presentStatements(response: Statement.StatementModels.Response)
    {
        let viewModel = Statement.StatementModels.ViewModel(statementModel: response.statementModel)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentLoading() {
        viewController?.displayLoading()
    }
    
    func removeLoading() {
        viewController?.removeLoading()
    }
}
