# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def podsiOS
  pod 'RxSwift', '6.1.0'
  # pod 'RxRelay, '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxAlamofire', '6.1.1'
end

target 'BankTesteiOSv2' do
  use_frameworks!
  podsiOS
end

  target 'BankTesteiOSv2Tests' do
    inherit! :search_paths
  end

  target 'BankTesteiOSv2UITests' do
  end

post_install do |installer|
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '5.0'
      end
   end
end
