# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def podsiOS
  pod 'LoginLibrary', :path => "~/Desktop/TesteiOSv2/Projects/Pods/LoginLibrary"
  pod 'BankStatementLibrary', :path => "~/Desktop/TesteiOSv2/Projects/Pods/BankStatementLibrary"
  pod 'ModelsLibrary' , :path => "~/Desktop/TesteiOSv2/Projects/Pods/ModelsLibrary"
  pod 'WorkersLibrary' , :path => "~/Desktop/TesteiOSv2/Projects/Pods/WorkersLibrary"
  pod 'ServicesLibrary' , :path => "~/Desktop/TesteiOSv2/Projects/Pods/ServicesLibrary"
end

target 'BankTesteiOSv2' do
  use_frameworks!
  podsiOS
end

  target 'BankTesteiOSv2Tests' do
    inherit! :search_paths
  end

  target 'BankTesteiOSv2UITests' do
  end

post_install do |installer|
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '5.0'
      end
   end
end
