//
//  LoginInteractor.swift
//  TestSantander-IBM
//
//  Created by Renato Carvalhan on 22/01/19.
//  Copyright (c) 2019 Renato Carvalhan. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol LoginInteractorInput {
     func postLogin(request: LoginScene.Login.Request, completionHandler: @escaping (Bool, String?) -> Void)
}

protocol LoginInteractorOutput {
    
}

protocol LoginDataSource {
    var userAccount: UserAccount! {get set}
}

protocol LoginDataDestination {
    
}

class LoginInteractor: LoginInteractorInput, LoginDataSource, LoginDataDestination {
    
    var output: LoginInteractorOutput?
    var userAccount: UserAccount!
    
    var networkManager: NetworkManager!
    
    init(networkManager: NetworkManager) {
        self.networkManager = networkManager
    }
    
    // MARK: Business logic
    
    func postLogin(request: LoginScene.Login.Request, completionHandler: @escaping (Bool, String?) -> Void) {
        networkManager.login(request: request) { (response, err) in
            if err != nil {
                completionHandler(false, err)
            } else {
                guard let userAccount = response?.userAccount else {
                    completionHandler(false, response?.error?.message)
                    return
                }
                
                self.userAccount = userAccount
                UserAccount.current = self.userAccount
                completionHandler(true, nil)
            }
        }
    }
}
