//
//  LoginViewController.swift
//  TesteiOS
//
//  Created by Fernando Gomes on 14/06/19.
//  Copyright (c) 2019 Fernando Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
    func displayStatmentView()
    func displayErrorMessage(title: String, message: String)
    func showLoading()
    func hideLoading()
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    func showLoading() {
        
    }
    
    func hideLoading() {
        
    }
    
    func displayErrorMessage(title: String, message: String) {
        hideLoading()
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Tente novamente", style: .default, handler: nil))
        present(alert, animated: true)
    }
    
    func displayStatmentView() {
        
    }
    
    

  var interactor: LoginBusinessLogic?
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    @IBOutlet weak var loginTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBAction func loginAction(_ sender: UIButton) {
        doLogin()
    }
    
    override func viewDidLoad()
  {
    super.viewDidLoad()
    view.endEditing(true)
  }
  

  
  func doLogin() {
    showLoading()
    let request = Login.doLogin.Request(user: loginTextField.text!, password: passwordTextField.text!)
    interactor?.doLogin(request: request)
  }
  
//  func displayStatmentView()
//  {
//    router?.goToStatments()
//    hideLoading()
//  }
}
