//
//  LoginPresenter.swift
//  TesteiOS
//
//  Created by Fernando Gomes on 14/06/19.
//  Copyright (c) 2019 Fernando Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentSomething(response: Login.doLogin.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Login.doLogin.Response)
  {
    let viewModel = Login.doLogin.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
