//
//  HomeWorker.swift
//  CleanSwift
//
//  Created by Samanta Clara Coutinho Rondon do Nascimento on 2019-08-02.
//  Copyright (c) 2019 Sam. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire

protocol HomeWorkerProtocol {
    func doSomeWork(request: Home.Request, completion:@escaping (Result<StatementList>) -> Void)
}

class HomeWorker: HomeWorkerProtocol {
    static let shared = HomeWorker()
    private lazy var apiWorker: APIWorker = {
        let manager = APIWorker()
        return manager
    }()
    
    func doSomeWork(request: Home.Request, completion:@escaping (Result<StatementList>) -> Void) {
        apiWorker.createRequest(route: API.home(userId: request.userId),
                                completion: completion)
    }
}
