//
//  StatementsInteractor.swift
//  BankApp-Desafio
//
//  Created by Mizia Lima on 2/26/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsBusinessLogic {
    func doSomething(request: Statements.Something.Request)
}

protocol StatementsDataStore {
    var user: UserAccount? { get set }
}

class StatementsInteractor: StatementsBusinessLogic, StatementsDataStore {
    var presenter: StatementsPresentationLogic?
    var worker: StatementsWorker?
   
    var user: UserAccount?
    
    // MARK: Do something
    
    func doSomething(request: Statements.Something.Request)
    {
        worker = StatementsWorker()
        worker?.doSomeWork()
        
        let response = Statements.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
