//
//  UserAccountBalanceInteractor.swift
//  TesteiOSV2_Rafael_Hieda
//
//  Created by Rafael  Hieda on 10/29/18.
//  Copyright (c) 2018 Rafael Hieda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserAccountBalanceBusinessLogic
{
  func doSomething(request: UserAccountBalance.Something.Request)
    func loadRegistry(ur: UserResponse)
}

protocol UserAccountBalanceDataStore
{
  //var name: String { get set }
}

class UserAccountBalanceInteractor: UserAccountBalanceBusinessLogic, UserAccountBalanceDataStore
{
    func loadRegistry(ur: UserResponse) {
        worker = BankAPIWorker()
        
    }
    
  var presenter: UserAccountBalancePresentationLogic?
  var worker: BankAPIWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UserAccountBalance.Something.Request)
  {
//    worker = UserAccountBalanceWorker()
//    worker?.doSomeWork()
    
    let response = UserAccountBalance.Something.Response()
    presenter?.presentSomething(response: response)
  }
    
}
