//
//  UserAccountBalanceRouter.swift
//  TesteiOSV2_Rafael_Hieda
//
//  Created by Rafael  Hieda on 10/29/18.
//  Copyright (c) 2018 Rafael Hieda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserAccountBalanceRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UserAccountBalanceDataPassing
{
  var dataStore: UserAccountBalanceDataStore? { get }
}

class UserAccountBalanceRouter: NSObject, UserAccountBalanceRoutingLogic, UserAccountBalanceDataPassing
{
  weak var viewController: UserAccountBalanceViewController?
  var dataStore: UserAccountBalanceDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: UserAccountBalanceViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: UserAccountBalanceDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
