//
//  StatementListInteractor.swift
//  TesteiOSv2
//
//  Created by Bruno on 09/11/18.
//  Copyright (c) 2018 Bruno Scheltzke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementListBusinessLogic
{
  func doSomething(request: StatementList.Something.Request)
}

protocol StatementListDataStore
{
    var userId: Int! { get set }
}

class StatementListInteractor: StatementListBusinessLogic, StatementListDataStore
{
  var presenter: StatementListPresentationLogic?
  var worker: StatementListWorker?
  var userId: Int!
  
  // MARK: Do something
  
  func doSomething(request: StatementList.Something.Request)
  {
    worker = StatementListWorker()
    worker?.doSomeWork()
    
    let response = StatementList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
