//
//  LoginModels.swift
//  TesteiOSv2Acc
//
//  Created by Marlon Santos Heitor on 21/05/19.
//  Copyright (c) 2019 Marlon Santos Heitor. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum FetchLoginData
    {
        struct Request
        {
            let user: String
            let password: String
        }
        struct Response
        {
            let user: String?
            let password: String?
            
            let isError: Bool
        }
        struct ViewModel
        {
            let user: String?
            let password: String?
            
            let errorMessage: String?
        }
    }
    
    enum LoginUser
    {
        struct Request
        {
            let user: String
            let password: String
        }
        struct Response
        {
            let userAccount: UserAccount?
            let serviceError: ServiceError?
        }
        struct ViewModel
        {
            let userAccount: UserAccount?
            let serviceError: ServiceError?
        }
    }
}
