//
//  LoginViewController.swift
//  TesteiOSv2_ArlenPereira
//
//  Created by Arlen Ricardo Pereira on 28/01/20.
//  Copyright (c) 2020 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import JGProgressHUD
import KeychainSwift

protocol LoginDisplayLogic: class
{
    func displayLogin(viewModel: LoginModel.LoginRequestModel.ViewModel)
    func displayValidationLogin(viewModel: LoginModel.ValidationLoginModel.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    
    // MARK: - Variable
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    let hud = JGProgressHUD(style: .dark)
    let loginSegue = "Statement"
    
    let keychain = KeychainSwift(keyPrefix: Keys.prefix)

  // MARK: - Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: - Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: - Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupProgressHUD()
    
    let gesture = UITapGestureRecognizer(target: self, action: #selector(self.dismissKeyboard (_:)))
    self.view.addGestureRecognizer(gesture)
    
    loginBtnOutlet.layer.cornerRadius = 5
    
    if let userNameIsSave = keychain.get(Keys.username) {
        usernameTextField.text = userNameIsSave
    }
    
  }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        if let userNameIsSave = keychain.get(Keys.username), let passwordIsSave = keychain.get(Keys.password) {
            login(username: userNameIsSave, password: passwordIsSave)
        }
    }
  
  // MARK: - Interface
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var usernameTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var loginBtnOutlet: UIButton!
    
    // MARK: - Function
    
    func setupProgressHUD()
    {
        hud.textLabel.text = "Loading"
    }
    
    @objc func dismissKeyboard(_ sender: UITapGestureRecognizer)
    {
        usernameTextField.resignFirstResponder()
        passwordTextField.resignFirstResponder()
    }
    
    func validationLogin(username: String, password: String)
    {
        hud.show(in: self.view, animated: true)
        let request = LoginModel.ValidationLoginModel.Request(username: username, password: password)
        interactor?.validationLoginRequest(request: request)
    }
    
    func login(username: String, password: String)
    {
        hud.show(in: self.view, animated: true)
        let request = LoginModel.LoginRequestModel.Request(username: username, password: password )
        interactor?.loginRequest(request: request)
    }
  
    func displayValidationLogin(viewModel: LoginModel.ValidationLoginModel.ViewModel)
    {
        hud.dismiss(afterDelay: 1.0, animated: true)
        if !viewModel.isUsernameValid {
            self.alert(message: viewModel.errorMessage)
        } else if !viewModel.isPasswordValid {
            self.alert(message: viewModel.errorMessage)
        } else {
            view.endEditing(true)
            
            if usernameTextField.text != "", passwordTextField.text != "" {
                guard let username = usernameTextField.text else { return }
                keychain.set(username, forKey: Keys.username, withAccess: .accessibleWhenPasscodeSetThisDeviceOnly)
                guard let password = passwordTextField.text else { return }
                keychain.set(password, forKey: Keys.password, withAccess: .accessibleWhenPasscodeSetThisDeviceOnly)
                
                login(username: username, password: password)
            }
        }
    }
    
    func displayLogin(viewModel: LoginModel.LoginRequestModel.ViewModel)
    {
        if !viewModel.data.isEmpty {
            passwordTextField.text?.removeAll()
            hud.dismiss(afterDelay: 1.0, animated: true)
            performSegue(withIdentifier: loginSegue, sender: nil)
        }
    }
    
    // MARK: - Button
    @IBAction func loginButton(_ sender: UIButton) {
        view.endEditing(true)
        if usernameTextField.text != "", passwordTextField.text != "" {
            guard let username = usernameTextField.text else { return }
            guard let password = passwordTextField.text else { return }
            
            validationLogin(username: username, password: password)
        }
    }
}

// MARK: - Extension
extension LoginViewController: UITextFieldDelegate
{
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == usernameTextField {
            textField.resignFirstResponder()
            passwordTextField.becomeFirstResponder()
        } else if textField == passwordTextField {
            textField.resignFirstResponder()
            if usernameTextField.text != "", passwordTextField.text != "" {
                validationLogin(username: usernameTextField.text ?? "", password: passwordTextField.text ?? "")
            }
        }
        return true
    }
}
