//
//  StatementListPresenter.swift
//  TestSantander-IBM
//
//  Created by Erika Albizzati on 26/10/18.
//  Copyright (c) 2018 Erika Albizzati. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol StatementListPresenterInput {
    func presentStatements(response: StatementListScene.GetStatements.Response)
}

protocol StatementListPresenterOutput: class {
    func displayStatements(viewModel: StatementListScene.GetStatements.ViewModel)
}

class StatementListPresenter: StatementListPresenterInput {
    
    weak var output: StatementListPresenterOutput?
    
    // MARK: Presentation logic
    func presentStatements(response: StatementListScene.GetStatements.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        var statementViewModel:[StatementListScene.GetStatements.ViewModel.Statements] = []
        for statement in response.statements {
            let title = statement.title
            let description = statement.desc
            let value = statement.value!
            let date = statement.date
            
            statementViewModel.append(StatementListScene.GetStatements.ViewModel.Statements(title: title!, description: description!, date: date!, value: Float(value)))
        }
        
        let viewModel = StatementListScene.GetStatements.ViewModel(statements: statementViewModel)
        output?.displayStatements(viewModel: viewModel)
    }

}
