# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'KssiusBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KssiusBank
  pod 'SwiftGen', '~> 6.6.2'
  pod 'KeychainSwift', '~> 20.0'

  target 'KssiusBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KssiusBankUITests' do
    # Pods for testing
  end

end
