# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOSSantander' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for TesteiOSSantander
	 pod 'DAKeychain'
	pod 'Alamofire'
  target 'TesteiOSSantanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteiOSSantanderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
