//
//  LoginPresenter.swift
//  Williamberg Bank
//
//  Created by padrao on 16/05/20.
//  Copyright (c) 2020 Williamberg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentLoginResult(response: Login.Login.Response)
  func presentUserSaved(response: Login.SavedUser.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Present Login Result
  func presentLoginResult(response: Login.Login.Response)
  {
    let viewModel = Login.Login.ViewModel(userAccount: response.userAccount, errorMessage: response.errorMessage)
    viewController?.displayLoginResult(viewModel: viewModel)
  }
    
    // MARK: Present User Saved Result
    func presentUserSaved(response: Login.SavedUser.Response)
    {
        let viewModel = Login.SavedUser.ViewModel(user: response.user, password: response.password)
        viewController?.displayUserSaved(viewModel: viewModel)
    }
}
