//
//  LoginModels.swift
//  Williamberg Bank
//
//  Created by padrao on 16/05/20.
//  Copyright (c) 2020 Williamberg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
        let user: String?
        let password: String?
    }
    struct Response
    {
        let userAccount: UserAccount?
        let errorMessage: String?
    }
    struct ViewModel
    {
        let userAccount: UserAccount?
        let errorMessage: String?
    }
  }
    
    enum SavedUser
    {
      struct Request
      {
      }
      struct Response
      {
          let user: String?
          let password: String?
      }
      struct ViewModel
      {
          let user: String?
          let password: String?
      }
    }
}
