//
//  StatementsWorker.swift
//  TesteiOSv2Acc
//
//  Created by Marlon Santos Heitor on 21/05/19.
//  Copyright (c) 2019 Marlon Santos Heitor. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class StatementsWorker
{
    var loadStatementsRestService: RestService<StatementsResponse>?
    
    // MARK: - Initialization
    
    required init(){
        loadStatementsRestService = RestService<StatementsResponse>()
    }
    
    // MARK: - Services
    
    func doLoadStatementsRequest(userId: Int, completion: @escaping ([Statement]?, ServiceError?) -> Void)
    {
        
        let serviceRequest = ServiceRequest.requestForStatements(userId: userId)
        
        loadStatementsRestService?.executeServiceRequest(serviceRequest: serviceRequest)
        { (statementsResponse, requestError) in
            
            if statementsResponse?.error?.code != nil{
                completion(nil, statementsResponse?.error)
            }else{
                completion(statementsResponse?.statementList, nil)
            }
            
        }
        
    }
    
    func cancelLoginRequest(){
        loadStatementsRestService?.cancelCurrentRequest()
    }
}
