//
//  StatementsModels.swift
//  TesteSantander
//
//  Created by Felipe Alexander Silva Melo on 29/05/19.
//  Copyright (c) 2019 Felipe Alexander Silva Melo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Statements {
  // MARK: Use cases
  
  enum Statements {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
