//
//  StatementsPresenter.swift
//  TesteSantander
//
//  Created by Felipe Alexander Silva Melo on 29/05/19.
//  Copyright (c) 2019 Felipe Alexander Silva Melo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsPresentationLogic {
    func displayStatements(response: Statements.Statements.Response)
    func displayErrorMessage(message: String)
}

class StatementsPresenter: StatementsPresentationLogic {
    weak var viewController: StatementsDisplayLogic?
    
    // MARK: Do something
    func displayStatements(response: Statements.Statements.Response) {
        let viewModel = Statements.Statements.ViewModel()
        viewController?.displayStatements(viewModel: viewModel)
    }
    
    func displayErrorMessage(message: String) {
        print("Display Error Message")
    }
    
}
