//
//  LoginRouter.swift
//  TesteiOSv2Project
//
//  Created by Andrey on 11/06/20.
//  Copyright (c) 2020 Andrey Matos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    @objc func routeToShowBalance(segue: UIStoryboardSegue?){
        if let segue = segue {
            let destinationVC = segue.destination as! UserBalanceViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowBalance(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "UserBalanceViewController") as! UserBalanceViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowBalance(source: dataStore!, destination: &destinationDS)
            navigateToShowBalance(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToShowBalance(source: LoginViewController, destination: UserBalanceViewController){
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToShowBalance(source: LoginDataStore, destination: inout UserBalanceDataStore){
        destination.userAccount = source.userAccount
    }
}
