//
//  LoginModels.swift
//  TesteiOSv2Project
//
//  Created by Andrey on 11/06/20.
//  Copyright (c) 2020 Andrey Matos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum FetchUser
  {
    struct Request
    {
        var credentials: UserCredentials
    }
    struct Response: Codable
    {
        struct Error: Codable {
            var code: Int?
            var message: String?
        }
        var userAccount: UserAccount?
        var error: Error?
    }
    struct ViewModel
    {
        
    }
  }
}
