//
//  ExtratoWorker.swift
//  TesteiOSv2
//
//  Created by Marcel Mendes Filho on 26/02/19.
//  Copyright (c) 2019 Accenture do Brasil Ltda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ExtratoWorker
{
    func retrieveStatement(completionResult: @escaping (StatementModel?, Bool) -> Void){
        NetworkRequest.shared.send(endPoint: Constants.Request.statements, httpMethod: Constants.httpMethod.GET, additionalHeaders: nil, parameters: nil, completionSuccess: { (data) in
            
            if let statement = StatementModel(data: data){
                print("Statement: ", statement)
                completionResult(statement, true)
                return
            } else {
                completionResult(nil, false)
            }
            
        }, completionError: { (serverErrorCode) in
            print(serverErrorCode)
            completionResult(nil, false)
        }) { (error) in
            print(error)
            completionResult(nil, false)
        }
    }
    
    
    
    
}
