excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - TesteiOSv2Tests
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - empty_count
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - first_where
  - for_where
  - force_cast
  - force_try
  - mark
  - multiline_parameters
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate
disabled_rules:
  - nesting
custom_rules:
  vertical_whitespace_opening_braces:
    included: ".*.swift"
    regex: '[{(\[][ \t]*\n[ \t]*\n'
    name: "Vertical Whitespace after Opening Braces"
    message: "Don't include vertical whitespace (empty line) after opening braces."
    severity: warning
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
