# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TesteiOSv2' do
  use_frameworks!

  pod 'Cartography'
  pod 'SwiftLint'

  target 'TesteiOSv2Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
