//
//  StatementsInteractor.swift
//  BankInterviewApp
//
//  Created by Osias Carneiro on 10/03/20.
//  Copyright (c) 2020 Osias Carneiro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsBusinessLogic
{
  func fetchStatements(request: Statements.StatementList.Request)
}

protocol StatementsDataStore
{
    var userData: Statements.UserData.ViewModel? { get set }
}

class StatementsInteractor: StatementsBusinessLogic, StatementsDataStore
{
  var presenter: StatementsPresentationLogic?
  var worker: StatementsWorker?
  var statementsWorker: FetchStatementsWorker = FetchStatementsWorker(store: StatementAPI())
  var userData: Statements.UserData.ViewModel?
  
  // MARK: Do something
  
  func fetchStatements(request: Statements.StatementList.Request)
  {
    statementsWorker.fetchStatements(userId: request.userId, completionHandler: { [weak self] response in
        if !response.statementList.isEmpty {
            var model = Statements.StatementList.ViewModel(statements: [])
            let transformed = response.statementList.map({
                Statements.StatementList.Statement(transaction: $0.title, description: $0.desc, date: $0.date, value: $0.value.formatToCoin())
            })
            model.statements.append(contentsOf: transformed)
            self?.presenter?.presentFetchedStatements(response: model)
        }
    })
  }
}
