//
//  LoginViewViewController.swift
//  challenge-santander
//
//  Created by Hugo Ferreira on 18/05/20.
//  Copyright (c) 2020 Hugo Ferreira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginViewDisplayLogic: class
{
    func displayInfoMessage(message: String)
}

class LoginViewController: UIViewController, UITextFieldDelegate, LoginViewDisplayLogic {
    
    
    @IBOutlet weak var logoImage: UILabel!
    @IBOutlet weak var userTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var loginButton: UIButton!
    
    
    var interactor: LoginBusinessLogic?
    var userDetails : UserModel?
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let worker = LoginWorker()
        viewController.interactor = interactor
        interactor.presenter = presenter
        interactor.worker = worker
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        userTextField?.delegate = self
        passwordTextField?.delegate = self
        
        logoImage?.layer.cornerRadius = 7
        logoImage?.layer.masksToBounds = true
        
        loginButton?.layer.shadowColor = UIColor.lightGray.cgColor
        loginButton?.layer.shadowOffset = CGSize(width: 3, height: 3)
        loginButton?.layer.shadowRadius = 4
        loginButton?.layer.cornerRadius = 4
        loginButton?.layer.shadowOpacity = 0.6
        setup()
    }
    
    @IBAction func loginButtonPressed(_ sender: UIButton) {
        let user = userTextField.text ?? ""
        let password = passwordTextField.text ?? ""
        interactor?.login(user : user, password : password)
    }
    
      // MARK: Message
    
    func displayInfoMessage(message: String) {
        let alert = UIAlertController(title: "Login Inválido", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: NSLocalizedString("OK", comment: "Default action"), style: .default, handler: { _ in
        }))
        
        self.present(alert, animated: true, completion: nil)
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        userTextField.endEditing(true)
        passwordTextField.endEditing(true)
        return true
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "goToHome" {
            let destinationVC = segue.destination as! HomeViewController
            destinationVC.userModel = userDetails
        }
    }
}
