disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- nesting
force_cast: warning
opt_in_rules:
- force_unwrapping
line_length:
- 200
- 300
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- R.generated.swift
- TesteSantanderTests
- TesteSantanderUITests
