# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'TesteSantander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteSantander
  pod 'SwiftLint'
  pod 'IQKeyboardManager'
  pod 'Moya/RxSwift'
  pod 'ViewAnimator'
  pod 'Hero'
  pod 'SnapKit'
  pod 'R.swift'

  target 'TesteSantanderTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'KIF'
    pod 'KIF/IdentifierTests'
  end

  target 'TesteSantanderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
