# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteSantander' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'SwiftKeychainWrapper'

  # Pods for TesteSantander

  target 'TesteSantanderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
