project 'Bank-App-CleanSwift.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bank-App-CleanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bank-App-CleanSwift
  pod 'Alamofire', '~> 5.2'

  target 'Bank-App-CleanSwiftTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end
end
