//
//  LoginPresenter.swift
//  Test Bank
//
//  Created by Lucas Santana Brito on 20/06/20.
//  Copyright (c) 2020 lsb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentSomething(response: Login.Response)
    func presentError(errorMessage: String)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
  
    func presentError(errorMessage: String) {
        let viewModel = Login.ViewModel(errorMesage: errorMessage)
        viewController?.showErrorLabel(viewModel: viewModel)
    }
    
    func presentSomething(response: Login.Response) {

        if let errorMessage = response.error?.message {
            let viewModel = Login.ViewModel(errorMesage: errorMessage)
            viewController?.showErrorLabel(viewModel: viewModel)
        } else {
            viewController?.hideErrorLabel()
        }

    }
}
