//
//  AccountModels.swift
//  TesteiOSv2
//
//  Created by Gilson Gil on 16/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Account {
  struct AccountDetails {
    var name: String
    var account: String
    var balance: String
  }

  enum ShowAccountDetails {
    struct Request {}
    struct Response {
      var userAccount: UserAccount
    }
    struct ViewModel {
      var accountDetails: AccountDetails
    }
  }
}
