//
//  StatementsListPresenter.swift
//  Bank_App
//
//  Created by apple on 21/03/20.
//  Copyright (c) 2020 Barbara_Aniele. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementsListPresentationLogic
{
  func presentSomething(response: StatementsList.Something.Response)
}

class StatementsListPresenter: StatementsListPresentationLogic
{
  weak var viewController: StatementsListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: StatementsList.Something.Response)
  {
    let viewModel = StatementsList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
