//
//  StatementsListWorker.swift
//  Bank_App
//
//  Created by apple on 21/03/20.
//  Copyright (c) 2020 Barbara_Aniele. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StatementsListWorker
{
  func doSomeWork()
  {
  }
}
