//
//  LoginPresenterTests.swift
//  Bank
//
//  Created by Matheus Rodrigues Ribeiro on 26/04/20.
//  Copyright (c) 2020 Bank. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TataSantanderBankTest
import XCTest

class LoginPresenterTests: XCTestCase
{
    // MARK: Subject under test
    var sut: LoginPresenter!
    let spy = LoginDisplayLogicSpy()
  
    // MARK: Test lifecycle

    override func setUp()
    {
        super.setUp()
        setupLoginPresenter()
    }

    override func tearDown()
    {
        super.tearDown()
    }

    // MARK: Test setup

    func setupLoginPresenter()
    {
        sut = LoginPresenter()
        sut.viewController = spy
    }

    // MARK: Test doubles
  
    class LoginDisplayLogicSpy: LoginDisplayLogic
    {
        var loginError: Login.UserData.Error?
        var sucess: Login.UserData.ViewModel?
        
        func displaySuccessLogin(viewModel: Login.UserData.ViewModel) {
            self.sucess = viewModel
        }
        
        func displayError(error: Login.UserData.Error) {
            self.loginError = error
        }
    }
  
    // MARK: Tests
    func testSucessLogin() {
        // Given
        let response = Login.UserData.Response(id: 1, name: "Matheus Rodrigues Ribeiro", agency: "0001", account: "000022", balance: 36.65)
        //When
        self.sut.presentLoginSucess(response: response)
        //Then
        XCTAssert(spy.sucess != nil && spy.sucess!.id == 1)
    }

    func testErrorLogin() {
        // Given
        let error = Login.UserData.Error(title: "Error", message: "Error to be shown")
        //When
        self.sut.presentError(error: error)
        //Then
        XCTAssert(spy.loginError != nil && spy.loginError!.message == "Error to be shown")
    }
}
