//
//  UserAccountModels.swift
//  BankApp
//
//  Created by Lynneker Souza on 5/29/20.
//  Copyright (c) 2020 Lynneker Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct UserAccount: Equatable, Decodable
{
    var userId: Int
    var name: String
    var bankAccount: String
    var agency: String
    var balance: Double
}

func ==(lhs: UserAccount, rhs: UserAccount) -> Bool
{
    return lhs.userId == rhs.userId
}
