//
//  DetailPresenter.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func present(response: Detail.Response)
    func presentUserInfo(response: Detail.Response)
}

class DetailPresenter: DetailPresentationLogic
{
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    
    func presentUserInfo(response: Detail.Response)
    {
        var viewModel = Detail.ViewModel()
        viewModel.name = response.name
        if let ac = response.agency, let ag = response.bankAccount {
           
            let mStr = NSMutableString(string: ac)
            mStr.insert("-", at: ac.count-1)
            mStr.insert(".", at: 2)
            viewModel.account = "\(ag) / \(mStr)"
        }
        
        let formatter = NumberFormatter()
        formatter.locale = Locale.current
        formatter.numberStyle = .currency
        if let bal = response.balance,
            let str = formatter.string(from: NSNumber(value: bal*1000)) {
            viewModel.balance = str
        }
        
        DispatchQueue.main.async {
            self.viewController?.displayUserInfo(viewModel: viewModel)
        }
        
    }
    
    func present(response: Detail.Response)
    {
//        let viewModel = Detail.ViewModel()
//        if response.success {
//            viewController?.displaySomething(viewModel: viewModel)
//        } else {
//            viewController?.displaySomething(viewModel: viewModel)
//        }
        
    }
}
