//
//  StatementRouter.swift
//  BankApp
//
//  Created by resource on 16/06/19.
//  Copyright (c) 2019 Gabriel Faustino. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StatementRoutingLogic{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol StatementDataPassing{
  var dataStore: StatementDataStore? { get }
}

class StatementRouter: NSObject, StatementRoutingLogic, StatementDataPassing{
  weak var viewController: StatementViewController?
  var dataStore: StatementDataStore?
  
}
