# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanSwift
	pod 'Alamofire', '5.0.0-beta.3'
	pod 'RealmSwift'
	pod 'IQKeyboardManagerSwift', '6.3.0'
	pod 'SVProgressHUD', '2.2.5'

  target 'CleanSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
