//
//  statementsRouter.swift
//  TesteIOS
//
//  Created by khalid ait bellahs on 21/01/19.
//  Copyright (c) 2019 ti alto nivel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol statementsRoutingLogic {
    func goToLogin()
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol statementsDataPassing {
    var dataStore: statementsDataStore? { get }
}

class statementsRouter: NSObject, statementsRoutingLogic, statementsDataPassing {
    weak var viewController: statementsViewController?
    var dataStore: statementsDataStore?
    let mainStoryBoard = UIStoryboard(name: "Main", bundle: Bundle.main)

    // MARK: Routing

    func goToLogin() {
        let loginViewController = LoginViewController()
        loginViewController.modalTransitionStyle = .coverVertical
        viewController?.present(loginViewController, animated: true, completion: nil)
    }
}
