//
//  LoginWorker.swift
//  TesteiOSv2
//
//  Created by Bruno on 09/11/18.
//  Copyright (c) 2018 Bruno Scheltzke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {
    private let localStorageService: LocalStorageServiceProtocol
    private let apiService: APIServiceProtocol
    
    init(_ localStorageService: LocalStorageServiceProtocol, _ apiService: APIServiceProtocol) {
        self.localStorageService = localStorageService
        self.apiService = apiService
    }
    
    func fetchExistingLoginInfo() -> (userName: String?, password: String?) {
        return localStorageService.loadLoginInfo()
    }
    
    func saveUserInfoLocally(userName: String, password: String) {
        localStorageService.setLoginInfo(userName: userName, password: password)
    }
    
    func performLogin(userName: String, password: String, completion: @escaping(Result<User>) -> Void) {
        apiService.performLogin(withUserName: userName, password: password, completion: completion)
    }
}
