//
//  LoginPresenter.swift
//  TesteiOSv2
//
//  Created by Gilson Gil on 15/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentError(response: Login.SubmitLogin.Response)
  func presentUserAccount(response: Login.SubmitLogin.Response)
}

final class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?

  func presentError(response: Login.SubmitLogin.Response) {
    let viewModel = Login.SubmitLogin.ViewModel(error: response.error)
    viewController?.displayError(viewModel: viewModel)
  }

  func presentUserAccount(response: Login.SubmitLogin.Response) {
    viewController?.displayUserAccount()
  }
}
