//
//  LoginWorker.swift
//  TesteiOSv2
//
//  Created by Bruno on 09/11/18.
//  Copyright (c) 2018 Bruno Scheltzke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {
    private let localStorageService: LocalStorageManagerProtocol
    
    init(_ localStorageService: LocalStorageManagerProtocol) {
        self.localStorageService = localStorageService
    }
    
    func fetchExistingLoginInfo() -> (userName: String?, password: String?) {
        return localStorageService.loadLoginInfo()
    }
}
