//
//  LoginPresenter.swift
//  TesteiOSv2
//
//  Created by Brendoon Ryos on 10/01/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentLoginErrorMessage(response: Login.Response)
  func presentLoginSucceeded(response: Login.Response)
  func presentFilledLoginTextFields(response: Login.TextFieldsData.Response)
}

class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Login Presentation Logic
  
  func presentLoginSucceeded(response: Login.Response) {
    let viewModel = Login.ViewModel(user: response.user, error: response.error)
    viewController?.displayLoginSucceeded(viewModel: viewModel)
  }
  
  func presentLoginErrorMessage(response: Login.Response) {
    let viewModel = Login.ViewModel(user: response.user, error: response.error)
    viewController?.displayLoginErrorMessage(viewModel: viewModel)
  }
  
  func presentFilledLoginTextFields(response: Login.TextFieldsData.Response) {
    let viewModel = Login.TextFieldsData.ViewModel(username: response.username, password: response.password)
    viewController?.displayFilledLoginTextFields(viewModel: viewModel)
  }
}
