//
//  LoginInteractor.swift
//  TesteiOSv2
//
//  Created by Gilson Gil on 15/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
  func getPersistedCredentials() -> Login.SubmitFields?
  func submitLogin(request: Login.SubmitLogin.Request)
}

protocol LoginDataStore {
  var userAccount: UserAccount? { get set }
}

final class LoginInteractor: LoginBusinessLogic, LoginDataStore {
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  var userAccount: UserAccount?

  // MARK: Submit Login

  func submitLogin(request: Login.SubmitLogin.Request) {
    worker = LoginWorker()
    do {
      try worker?.validateUser(fields: request.fields)

      worker?.submitLogin(request: request) { response in
        if response.userAccount != nil {
          self.userAccount = response.userAccount
          self.presenter?.presentUserAccount(response: response)
        } else {
          self.presenter?.presentError(response: response)
        }
      }
    } catch {
      let response = Login.SubmitLogin.Response(userAccount: nil, error: error as? ErrorProtocol)
      presenter?.presentError(response: response)
    }
  }

  func getPersistedCredentials() -> Login.SubmitFields? {
    return worker?.getPersistedCredentials()
  }
}
