//
//  LoginWorker.swift
//  TesteiOSv2
//
//  Created by Alex Nunes da Silva on 12/01/19.
//  Copyright (c) 2019 Alex Nunes da Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class LoginWorker
{
    typealias LoginWorkerScreensHandler = (UserModel) -> Swift.Void
    typealias LoginWorkerScreenFailure  = (NSError)-> Swift.Void

    func sendLogin(login : Login.LoginLoad.Request.Login,  completion : @escaping LoginWorkerScreensHandler, failure : @escaping LoginWorkerScreenFailure) {

        let logParameters = ["user" : login.login, "password" : login.senha]
        let requestable = loginWorkerRequestable(params: logParameters)
        let request     : HTTRequest<UserModel> = HTTRequest(requestable: requestable)

        
        request.post(success: { response in
            guard let login = response else {
                return
            }
            completion(login)
        }, failure: { error in
            failure(error)
        })
    }
}

struct loginWorkerRequestable : HTTPRequestable {
    
    var request : Login.LoginLoad.Request.Login{
        return Login.LoginLoad.Request.Login()
    }
    
    var url: URL {
        return URL(string: environment.host + path)!
    }
    
    var path: String {
        return "login"
    }
    
    var params: [String : Any]
}

