# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteSantander_Isabella' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteSantander_Isabella
  pod 'Alamofire', '~> 5.0.0-beta.5' 
  pod 'CPF-CNPJ-Validator'

end
