//
//  StatementViewController.swift
//  TesteiOS
//
//  Created by Fernando Gomes on 15/06/19.
//  Copyright (c) 2019 Fernando Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementDisplayLogic: class
{
  func updateViews(viewModel: Statements.get.ViewModel)
}

class StatementViewController: UIViewController, StatementDisplayLogic {
    var interactor: StatementBusinessLogic?
    var router: (NSObjectProtocol & StatementRoutingLogic & StatementDataPassing)?
    var repository: UserRepository?

    var statements: [Statement] = [] {
        didSet {
            DispatchQueue.main.async {
                self.statementsTableView.reloadData()
            }
        }
    }
    
    
    


  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = StatementInteractor()
    let presenter = StatementPresenter()
    let router = StatementRouter()
    let repository = UserRepository.shared
    
    viewController.interactor = interactor
    viewController.router = router
    viewController.repository = repository
    interactor.presenter = presenter
    interactor.userRepository = repository
    presenter.viewController = viewController
    presenter.repository = repository
    router.viewController = viewController
    router.dataStore = interactor
    
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var accountLabel: UILabel!
    @IBOutlet weak var balanceLabel: UILabel!
    @IBOutlet weak var statementsTableView: UITableView!
    
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupTableView()
    loadStatements()
    
  }
  
  // MARK: Do something
   
    func setupTableView() {
        let nib = UINib(nibName: "StatementTableViewCell", bundle: nil)
        let headerNib = UINib(nibName: "StatementTableViewHeaderCell", bundle: nil)
        statementsTableView.register(nib, forCellReuseIdentifier: StatementTableViewCell.identifier)
        statementsTableView.register(headerNib, forCellReuseIdentifier: StatementTableViewHeaderCell.identifier)
        statementsTableView.dataSource = self
        statementsTableView.delegate = self
    }
  
    func updateViews(viewModel: Statements.get.ViewModel) {
        
    let userAccount = viewModel.userAccount!
    statements = viewModel.statements!
    nameLabel.text = userAccount.name
        accountLabel.text = userAccount.bankAccount + " / " + userAccount.agency.bankAccountFormatter() 
    balanceLabel.text = userAccount.balance.changeCurrency()!

    }
    
    func loadStatements() {
        interactor?.updateStatementList()
    }
}

extension StatementViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let statement = statements[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "statementCell") as! StatementTableViewCell
        cell.setStatement(statement: statement)
        cell.addShadow()
        return cell
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return statements.count
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        guard let header = tableView.dequeueReusableCell(withIdentifier: StatementTableViewHeaderCell.identifier) else
        {
            return UIView()
        }
        
        return header
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 40
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 80
    }
    
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return 12.0
    }
}

extension UIView {
    func addShadow(){
        self.layer.shadowColor = UIColor.black.cgColor
        self.layer.shadowOpacity = 0.2
        self.layer.shadowRadius = 2.0
        self.layer.cornerRadius = 6.0
        self.layer.shadowOffset = CGSize.init(width: 1.0, height: 1.0)
    }
}
