//
//  LoginModels.swift
//  KssiusBank
//
//  Created by Cassio Sousa on 15/06/23.
//  Copyright (c) 2023 Cassio Sousa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {

    // MARK: Use cases

    enum FetchUser {
        struct Request {}

        struct Response {
            var user: String?
        }

        struct ViewModel {
            var user: String?
        }
    }

    enum Login {
        struct Request {
            var user: String?
            var password: String?
        }

        struct Response {
            let success: Bool
            let errorMessage: String?

            init(success: Bool = false, errorMessage: String? = nil) {
                self.success = success
                self.errorMessage = errorMessage
            }

            func toViewModel() -> ViewModel {
                return .init( success: success, errorMessage: errorMessage)
            }
        }

        struct ViewModel {
            var success: Bool
            var errorMessage: String?

            init(success: Bool = false, errorMessage: String? = nil) {
                self.success = success
                self.errorMessage = errorMessage
            }
        }
    }
}
