# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bank App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bank App
    pod 'KeychainSwift', '~> 13.0'
    pod 'TPKeyboardAvoiding', :git => 'https://github.com/michaeltyson/TPKeyboardAvoiding.git'
    
    target 'Bank AppUITests' do
      pod 'KIF'
    end
end
