//
//  LoginModels.swift
//  BankApp
//
//  Created by resource on 16/06/19.
//  Copyright (c) 2019 Gabriel Faustino. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    enum User {
        struct Request {
            let user: String?
            let password: String?
        }
        
        struct Response: Codable {
            let userAccount: UserAccount?
            let loginError: LoginError?
        }
        
        struct UserAccount: Codable {
            let userId: Int
            let name: String
            let bankAccount: String
            let agency: String
            let balance: Double
            
            enum CodingKeys: String, CodingKey {
                case userId = "userId"
                case name = "name"
                case bankAccount = "bankAccount"
                case agency = "agency"
                case balance = "balance"
            }
        }
        
        struct LoginError: Codable {
            let code: Int
            let message: String
            
            enum CodingKeys: String, CodingKey {
                case code = "code"
                case message = "message"
            }
        }
        
        struct ViewModel {
            let code: Int
            let message: String
            
            init(from model: Login.User.LoginError) {
                code = model.code
                message = model.message
            }
        }
    }
}
