platform :ios, '9.0'

target 'santander-challenge' do
  use_frameworks!

  # Pods for santander-challenge
  pod 'Alamofire', '~> 4.9.1'
  pod 'IQKeyboardManager', '~> 6.5.0'
  pod 'SwiftyJSON', '~> 5.0.0'

  target 'santander-challengeTests' do
    inherit! :search_paths

    # Pods for testing
  end
end
