//
//  StatementListWorker.swift
//  BankApp
//
//  Created by José Inácio Athayde Ferrarini on 17/03/20.
//  Copyright (c) 2020 br.com.solutis.inacioferrarini. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StatementListWorker {

    func fetchStatements(completion: @escaping ((Result<StatementList.Statements.Response?, Error>) -> Void)) {
        
        guard let apiUrl = URL(string: "https://bank-app-test.herokuapp.com/api/statements/1") else { return }
        
        var request = URLRequest(url: apiUrl)
        request.addValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        
        request.httpMethod = "GET"
        
        URLSession.shared.dataTask(with: request) { data, _, error in
            if let error = error {
                DispatchQueue.main.async {
                    completion(.failure(error))
                }
            } else {
                var response: StatementList.Statements.Response?
                if let data = data {
                    response <-- data
                }
                DispatchQueue.main.async {
                    completion(.success(response))
                }
            }
        }.resume()
    }
    
}
