//
//  LoginInteractor.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func auth(request: Home.Login.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker!
  //var name: String = ""
  
  
}

extension LoginInteractor: LoginBusinessLogic {
    func auth(request: Home.Login.Request) {
        var response = Home.Login.Response()
        let validationId = worker.validateId(request.id)
        let validationPassword = worker.validatePassword(request.password)
        response.id = validationId
        response.password = validationPassword
        if validationId, validationPassword {
            // save data
        }
        presenter?.present(response: response)
    }
}
