//
//  LoginPresenter.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func present(response: Login.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func present(response: Login.Response) {
        var viewModel = Login.ViewModel()
        if let msg = response.error?.message {
            viewModel.error = msg
        }
        DispatchQueue.main.async {
            self.viewController?.display(viewModel: viewModel)
        }
    }
}
