//
//  LoginModels.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login{
    
    struct Request: APIRequest {
        typealias Response = Login.Response
        
        var user: String?
        var password: String?
    }
    
    struct Response: Codable {
        var userAccount: Login.UserAccount?
        var error: Login.Error?
        
        var success: Bool { return userAccount?.userId != nil}
    }
    
    struct Error: Codable {
        var code: Int?
        var message: String?
    }
    
    struct UserAccount: Codable {
        var userId: Int?
        var name: String?
        var bankAccount: String?
        var agency: String?
        var balance: Double?
    }
    
    struct ViewModel {
        var error: String?
    }
    
}
