# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'Teste Santander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Teste Santander
  pod 'SnapKit'


  target 'Teste SantanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Teste SantanderUITests' do
    # Pods for testing
  end

end
