# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'SantanderSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SantanderSample
  pod 'Swinject', '2.5.0'
  pod 'IQKeyboardManager', '6.2.0'

end
