//
//  HomeRouter.swift
//  CleanSwift
//
//  Created by Samanta Clara Coutinho Rondon do Nascimento on 2019-08-02.
//  Copyright (c) 2019 Sam. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  func routeToSomewhere(home: HomeViewController)
}

class HomeRouter: NSObject, HomeRoutingLogic {
    var rootViewController: UIViewController { return navigationController }
    
    //This is navigation controller and where will be import
    //the navigationController's custom.
    private lazy var navigationController: UINavigationController = {
        let navigationController = CSNavigationController(rootController: nil)
        return navigationController
    }()

  // MARK: Routing
    func routeToSomewhere(home: HomeViewController) {
        home.dismiss(animated: true, completion: nil)
        
        let login = LoginViewController(interactor: LoginInteractor(worker: LoginWorker()), router: LoginRouter(), presenter: LoginPresenter())
        navigationController.present(login, animated: true, completion: nil)
    }
}
