disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - function_body_length
  - identifier_name
  - empty_count
  - type_name
  - large_tuple
  - todo
  - nesting
  - vertical_whitespace

opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Feature
  - Carthage
  - Modules
  - MovieListTests
  - MovieListUITests
  - MovieList/Modules
  

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
function_body_length:
  warning: 50
  error: 60

line_length: 200

identifier_name:
  excluded: # excluded via string array
    - id
    - URL

reporter: "xcode"

