project 'BankApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  def testing_pods
      pod 'Quick'
      pod 'Nimble'
  end
  
  
  # Pods for BankApp
  pod 'Alamofire', '~> 5.2'

  target 'BankAppTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end
end

