# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankApp

  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod 'KeychainSwift', '~> 13.0'

  target 'BankAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
