//
//  LoginRouter.swift
//  BankApp
//
//  Created by José Inácio Athayde Ferrarini on 17/03/20.
//  Copyright (c) 2020 br.com.solutis.inacioferrarini. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToStatementsList()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {

    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let statementListIdentifier = "StatementListViewController"
    
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?

    // MARK: Navigation
    
    func routeToStatementsList() {
        guard let destinationViewController = storyboard.instantiateViewController(withIdentifier: statementListIdentifier) as? StatementListViewController else { return }
        guard var destinatioDataStore = destinationViewController.router?.dataStore else { return }
        guard let dataStore = dataStore else { return }
        passDataToStatementList(source: dataStore, destination: &destinatioDataStore)
        viewController?.navigationController?.pushViewController(destinationViewController, animated: true)
    }

    // MARK: Passing data
    
    private func passDataToStatementList(source: LoginDataStore, destination: inout StatementListDataStore) {
        destination.userData = source.userData
    }

}
