//
//  LoginModels.swift
//  Bank App
//
//  Created by Christian Castro on 28/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  
  enum Something {
    struct Request {
        var user: String?
        var password: String?
    }
    
    struct Response {
        var userInfo: User?
        var user: String?
        var password: String?
        var errorMessage: String?
    }
    
    struct ViewModel {
        var userID: Int?
        var user: String?
        var password: String?
        var errorMessage: String?
    }
  }
}
