//
//  LoginRouter.swift
//  BankTest
//
//  Created by Jaber Vieira Da Silva Shamali on 05/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic{
    func routeToDetail(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing{

    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?

    // MARK: Routing
    
    func routeToDetail(segue: UIStoryboardSegue?) {
        if segue != nil {
    //      let destinationVC = segue.destination as! SomewhereViewController
    //      var destinationDS = destinationVC.router!.dataStore!
    //      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
          let storyboard = UIStoryboard(name: "Main", bundle: nil)
          let destinationVC = storyboard.instantiateViewController(withIdentifier: "AccountDetailViewController") as! AccountDetailViewController
          var destinationDS = destinationVC.router!.dataStore!
          passDataToSomewhere(source: dataStore!, destination: &destinationDS)
          navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    func navigateToSomewhere(source: LoginViewController, destination: AccountDetailViewController)
    {
      source.show(destination, sender: nil)
    }

    // MARK: Passing data

    func passDataToSomewhere(source: LoginDataStore, destination: inout AccountDetailDataStore){
        destination.clienteData   = source.clienteData
    }
}
