//
//  LoginViewControllerTests.swift
//  TesteiOSv2
//
//  Created by Bruno on 09/11/18.
//  Copyright (c) 2018 Bruno Scheltzke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteiOSv2
import XCTest

class LoginViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LoginViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupLoginViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLoginViewController()
  {
    sut = LoginViewController()
  }
  
  func loadView()
  {
    window.rootViewController = sut
    window.makeKeyAndVisible()
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
class LoginBusinessLogicSpy: LoginBusinessLogic {
    var verifyExistingLoginInfoCalled = false

    func verifyExistingLoginInfo(request: Login.ExistingInfo.Request) {
        verifyExistingLoginInfoCalled = true
    }
    
    func perfomLogin(request: Login.Login.Request) {}
}
  
    // MARK: Tests
  
    func testShouldVerifyExistingLoginInfoWhenViewIsLoaded() {
        // Given
        let spy = LoginBusinessLogicSpy()
        sut.interactor = spy

        // When
        loadView()

        // Then
        XCTAssertTrue(spy.verifyExistingLoginInfoCalled, "viewDidLoad() should ask the interactor to verify if there is existing loggin info")
    }
}
