//
//  LoginWorkerTests.swift
//  TesteiOSv2
//
//  Created by Bruno on 09/11/18.
//  Copyright (c) 2018 Bruno Scheltzke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteiOSv2
import XCTest

class LoginWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: LoginWorker!
    var localStorageService: MockLocalStorageService!
    var apiService: MockAPIService!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupLoginWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupLoginWorker() {
        localStorageService = MockLocalStorageService()
        apiService = MockAPIService()
        sut = LoginWorker(localStorageService, apiService)
    }
}
