# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bank_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bank_App
  pod 'Alamofire'

  target 'Bank_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bank_AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
