//
//  HomeInteractor.swift
//  TesteiOSv2
//
//  Created by Mônica Marques on 11/03/20.
//  Copyright (c) 2020 Mônica Marques. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    var user: User? { get set }
    func doSomething(request: Home.Something.Request)
    func getUserInfo()
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var user: User?
    
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Home.Something.Request)
    {
        worker = HomeWorker()
        worker?.doSomeWork()
        
        let response = Home.Something.Response()
//        presenter?.presentSomething(response: response)
    }
    
    func getUserInfo() {
        guard let user = self.user else {
            return
        }
        
        self.presenter?.presentUserInfos(with: user)
    }
}
