//
//  HomeModels.swift
//  TesteiOSv2
//
//  Created by Mônica Marques on 11/03/20.
//  Copyright (c) 2020 Mônica Marques. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel {
        var name: String
        var bankAgencyAccount: String
        var balance: String
    }
  }
}

struct StatementsResponse: Codable {
    var statementList: [Statements]?
    var error: Error?
}

struct Statements: Codable {
    var title: String?
    var desc: String?
    var date: String?
    var value: Double?
}
