//
//  HomeModels.swift
//  TesteiOSv2
//
//  Created by Alexandre Gabassi on 30/10/18.
//  Copyright (c) 2018 Alexandre Gabassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Register
{
    var title : String
    var desc : String
    var date : String
    var value : Float32
}

enum Home
{
  // MARK: Use cases
    enum GetUserInfo
    {
        struct Request
        {
        }
        struct Response
        {
            var userInfo: UserInfo
        }
        struct ViewModel
        {
            struct DisplayedUserInfo
            {
                var userId  : String?
                var name    : String?
                var bankAccount : String?
                var agency : String?
                var balance : String?
            }
            var displayedUserInfo: DisplayedUserInfo
        }
    }

    
    struct DisplayedRegister
    {
        var title : String
        var desc : String
        var date : String
        var value : String
    }

  enum FetchRegisters
  {
    struct Request
    {
        var userId: String
    }
    struct Response
    {
        var success: Bool
        var registers: [Register]
    }
    struct ViewModel
    {
        var displayedRegisters: [DisplayedRegister]
        var success: Bool
    }
  }
}
